export {
  Attachment,
  AttachmentEmpty,
  AttachmentHoverCard,
  AttachmentHoverCardContent,
  AttachmentHoverCardTrigger,
  AttachmentInfo,
  AttachmentPreview,
  AttachmentRemove,
  Attachments,
  getAttachmentLabel,
  getMediaCategory,
  useAttachmentContext,
  useAttachmentsContext,
  type AttachmentData,
  type AttachmentMediaCategory,
  type AttachmentProps,
  type AttachmentVariant,
  type AttachmentsProps,
} from '@/components/ai-elements/attachments';
